# Docker-compose pour Regest et ses services
# Version 1.0
# Auteur : Manon ANGELI et Mathis REGESTE
# Date : 2023-02-17

version : '3.9'

# Les variables d'environnement sont déclarée dans le fichier .env

# Liste des services
services:

  # Application Regest
  regest:
    image: regest/regest:${VERSION_REGEST}
    container_name: ${NOM_REGEST}
    restart:  always
    ports:
      - "${PORT_REGEST}:3000"
    environment:
      ## Pour bdd_config
      DOCKER_PROD: ${DOCKER_PROD}
      IP_MYSQL: ${IP_MYSQL}
      PORT_MYSQL: ${PORT_MYSQL}
      USER_MYSQL: ${USER_MYSQL}
      PASSWORD_MYSQL: ${PASSWORD_MYSQL}
      DATABASE_MYSQL: ${DATABASE_MYSQL}
      RACINE: ${RACINE}
    volumes:
      - ./regest:/usr/src/app/Regest:rw

    networks:
      dockerNetwork:
        ipv4_address: ${IP_REGEST}

  # Base de données MySQL
  database:
    image: mariadb:latest
    container_name: ${NOM_MYSQL}
    restart: always
    expose:
      - ${PORT_MYSQL}
    ports:
      - "${PORT_MYSQL}:3306"
    volumes:
      - ./bdd_regest.sql:/docker-entrypoint-initdb.d/bdd_regest.sql
      - ./bdd:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: ${DATABASE_MYSQL}
      MYSQL_USER: ${USER_MYSQL}
      MYSQL_PASSWORD: ${PASSWORD_MYSQL}
    networks:
      dockerNetwork:
        ipv4_address: ${IP_MYSQL}

  # Serveur SSH
  ssh:
    image: linuxserver/openssh-server:latest
    container_name: ${NOM_SSH}
    restart: always
    ports:
      - "${PORT_SSH}:22"
    volumes:
      - ./regest:/regest:rw
    environment:
      SUDO_ACCESS: "false"
      PASSWORD_ACCESS: "true"
      USER_NAME: ${USER_SSH}
      USER_PASSWORD: ${PASSWORD_SSH}
    networks:
      dockerNetwork:
        ipv4_address: ${IP_SSH}
 
  # Serveur PhpMyAdmin pour administation de la BDD
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    container_name: ${NOM_PHPMYADMIN}
    restart: always
    expose:
      - ${PORT_PHPMYADMIN}
    ports:
      - "${PORT_PHPMYADMIN}:80"
    environment:
      - PMA_HOST=${IP_MYSQL}
      - PMA_PORT=${PORT_MYSQL} 
    networks:
      dockerNetwork:
        ipv4_address: ${IP_PHPMYADMIN}

# Réseau Docker pour les services
networks:
  dockerNetwork:
    ipam:
      driver: default
      config: 
        - subnet: ${SUBNET_NETWORK}
