version : '3.9'

services:
  regest:
    image: regest/regest:bugs-Manon
    container_name: regest
    ports:
      - "80:3000"
    environment:
      DOCKER_TEST: 'true'
    volumes:
      - ./regest:/regest/comptes_rendus:rw
    restart:  always
    networks:
      dockerNetwork:
        ipv4_address: "192.168.90.30"

  database:
    image: mariadb:latest
    container_name: database
    expose:
      - "4000"
    ports:
      - "4000:3306"
    volumes:
      - ./bdd/bdd_regest.sql:/docker-entrypoint-initdb.d/bdd_regest.sql
      - ./bdd:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: regest
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      dockerNetwork:
        ipv4_address: "192.168.90.31"

  ssh:
    image: linuxserver/openssh-server:latest
    container_name: ssh
    ports:
      - "2222:22"
    restart: always
    volumes:
      - ./regest:/regest/comptes_rendus:rw
    environment:
      SUDO_ACCESS: "false"
      PASSWORD_ACCESS: "true"
      USER_NAME: user
      USER_PASSWORD: password
    networks:
      dockerNetwork:
        ipv4_address: "192.168.90.32"
 
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    expose:
      - "4001"
    ports:
      - "4001:80"
    environment:
      - PMA_HOST=192.168.90.31
      - PMA_PORT=3306 
    restart: always
    networks:
      dockerNetwork:
        ipv4_address: "192.168.90.33"

networks:
  dockerNetwork:
    ipam:
      driver: default
      config: 
        - subnet: "192.168.90.0/24"
